"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Check } from "lucide-react";

type Product = { _id: string; name: string; price: number; discount?: number; stock: number; colors?: string[]; sizes?: string[]; description?: string; productImgUrls?: string[]; brand?: { name: string } | string; category?: { name: string } | string };
export default function ComparePage() {
  const [products, setProducts] = useState<Product[]>([]);
  const api = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";
  useEffect(() => { const ids = JSON.parse(localStorage.getItem("compareProducts") || "[]") as string[]; if (!ids.length) return; fetch(`${api}/product/getAll`).then((r) => r.json()).then((result) => setProducts((result.data || []).filter((item: Product) => ids.includes(item._id)))).catch(() => setProducts([])); }, [api]);
  const remove = (id: string) => { const ids = JSON.parse(localStorage.getItem("compareProducts") || "[]").filter((item: string) => item !== id); localStorage.setItem("compareProducts", JSON.stringify(ids)); setProducts((items) => items.filter((item) => item._id !== id)); window.dispatchEvent(new Event("compareUpdated")); };
  const rows: Array<[string, (product: Product) => string]> = [["Price", (p) => `₹${Math.round(p.discount ? p.price * (1 - p.discount / 100) : p.price).toLocaleString("en-IN")}`], ["Brand", (p) => typeof p.brand === "object" ? p.brand?.name || "—" : p.brand || "—"], ["Category", (p) => typeof p.category === "object" ? p.category?.name || "—" : p.category || "—"], ["Availability", (p) => p.stock > 0 ? "In stock" : "Out of stock"], ["Sizes", (p) => p.sizes?.join(", ") || "—"], ["Colors", (p) => p.colors?.join(", ") || "—"]];
  return <div className="container mx-auto min-h-screen px-4 py-8"><Link href="/products" className="mb-6 inline-flex items-center gap-2 text-sm text-orange-600"><ArrowLeft className="h-4 w-4" /> Continue shopping</Link><h1 className="mb-2 text-3xl font-bold text-gray-900 dark:text-white">Compare products</h1><p className="mb-6 text-sm text-gray-500">Compare up to 4 sports products side by side.</p>{!products.length ? <div className="rounded-2xl border bg-white p-12 text-center text-gray-500 dark:bg-gray-800">Select products using the compare icon to get started.</div> : <div className="overflow-x-auto rounded-2xl border bg-white dark:bg-gray-800"><table className="min-w-[680px] w-full text-left text-sm"><tbody><tr><th className="w-40 p-4 text-gray-500">Product</th>{products.map((p) => <td key={p._id} className="p-4 align-top"><img src={`${p.productImgUrls?.[0]?.startsWith("http") ? p.productImgUrls[0] : `${api}/uploads/${p.productImgUrls?.[0] || ""}`}`} alt={p.name} loading="lazy" className="mb-3 h-32 w-full rounded-lg bg-gray-50 object-contain" /><Link href={`/product/${p._id}`} className="font-semibold hover:text-orange-600">{p.name}</Link><button onClick={() => remove(p._id)} className="mt-2 block text-xs text-red-500">Remove</button></td>)}</tr>{rows.map(([label, get]) => <tr key={label} className="border-t"><th className="p-4 text-gray-500">{label}</th>{products.map((p) => <td key={p._id} className="p-4">{get(p)}</td>)}</tr>)}</tbody></table></div>}</div>;
}
